apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-app-web
spec:
  project: infrastructure
  sources: 
    - repoURL: 'https://example.com/test-repo/test.git'
      path: infrastructure/karpenter/helm/overlays/web-cluster
      targetRevision: master
    - repoURL: 'https://example.com/test-repo/test.git'
      path: infrastructure/karpenter/application/overlays/web-cluster
      targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
