apiVersion: v1
kind: Secret
metadata:
  name: gitlab-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://example.com/test-repo/test.git
  username: argocd
  password: 8Lvx.. # PAT
