apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: was-cluster-secret
  namespace: argocd
spec:
  encryptedData:
    config: AgCq..
    name: AgAa..
    server: AgBH..
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: cluster
      name: was-cluster-secret
      namespace: argocd
    type: Opaque