apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-test-app-hpa
spec:
  maxReplicas: changeme
  minReplicas: changeme
  scaleTargetRef:
    apiVersion: apps/v1          
    kind: Deployment                  
    name: backend-test-app
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: changeme
          averageUtilization: changeme
    - type: Resource
      resource:
        name: memory
        target:
          type: changeme
          averageValue: changeme