apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-custom
  namespace: argocd
spec:
  source:
    repoURL: 'https://example.com/test-repo/test.git'
    targetRevision: master
    path: infrastructure/argocd/resources/overlays/web-cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system