apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: albc-custom
  namespace: argocd
spec:
  source:
    repoURL: 'https://example.com/test-repo/test.git'
    targetRevision: master
    path: infrastructure/albc/resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system