apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: workload
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-was-test-stg-an1-01"
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: "eks-was-test-stg-an1-01"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 120Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true