apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: albc
  namespace: argocd
spec:
  source:
    targetRevision: 1.14.1
    helm:
      valuesObject:
        serviceAccount:
          name: aws-load-balancer-controller
        clusterName: eks-was-test-stg-an1-01
        vpcId: vpc-1111222233334444
  destination:
    namespace: kube-system
    server: 'https://1234ABCD.gr7.ap-northeast-1.eks.amazonaws.com'