apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.91.1
    helm:
      releaseName: opentelemetry-operator
      valuesObject:
        manager:
          collectorImage:
            tag: v0.43.3
  destination:
    server: 'https://1234ABCD.gr7.ap-northeast-1.eks.amazonaws.com'
    namespace: opentelemetry-operator-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true