apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
spec:
  description: changeme
  sourceRepos:
    - changeme
  destinations:
    - namespace: changeme
      server: changeme