apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-creds
  namespace: argocd
spec:
  encryptedData:
    password: changeme
    url: changeme
    username: changeme
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: changeme
      name: changeme
      namespace: changeme