apiVersion: v1
kind: Secret
metadata:
  name: gitlab-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: changeme
  username: changeme
  password: changeme
