apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: was-cluster-secret
  namespace: argocd
spec:
  encryptedData:
    config: changeme
    server: changeme
    name: changeme
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: changeme
      name: changeme
      namespace: changeme
    type: changeme