apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-app
spec:
  project: infrastructure
  source:
    repoURL: 'https://example.com/test-repo/test.git'
    targetRevision: master
    path: infrastructure/sealed-secret/helm/overlays/web-cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true