apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-test-app
  namespace: argocd
spec:
  project: app
  source:
    repoURL: changeme
    targetRevision: master
    path: changeme
  destination:
    server: changeme
    namespace: changeme