apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  source:
    helm:
      valuesObject:
        global:
          domain: test-argocd-stg.example.com
        configs:
          secret:
            argocdServerAdminPassword: $2a$12$dbj # brcypted.
            extra:
              accounts.sjju.password: $2y$12$oJo
              accounts.sjju2.password: $2y$12$QWP
          cm:
            accounts.sjju: login, apikey
            accounts.sjju2: login, apikey
          rbac:
            policy.default: role:readonly
            policy.csv: |
              p, role:admin, applications, *, *, allow
              p, role:admin, clusters, *, *, allow
              p, role:admin, repositories, *, *, allow
              p, role:admin, projects, *, *, allow
              p, role:admin, accounts, *, *, allow
              g, sjju, role:admin
              g, sjju2, role:admin
        server:
          ingress:
            annotations:
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:ACCOUNT_NUMBER:certificate/111111-2222-3333-4444
              alb.ingress.kubernetes.io/group.name: test-stg-web
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'