apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  source:
    helm:
      valuesObject:
        global:
          domain: test-argocd-stg.example.com
        configs:
          secret:
            argocdServerAdminPassword: $2a$12$dbj # brcypted.
        server:
          ingress:
            annotations:
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:ACCOUNT_NUMBER:certificate/111111-2222-3333-4444
              alb.ingress.kubernetes.io/group.name: test-stg-web
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'